export const seedUsers = [
    {
        id: 'user_alice_silva',
        nome: 'Alice Silva',
        email: 'alice.silva@email.com',
        cargo: 'Desenvolvedora Full Stack',
        habilidadesTecnicas: ['React', 'Node.js', 'Python', 'MongoDB', 'PostgreSQL'],
        softSkills: ['Liderança', 'Comunicação', 'Criatividade', 'Empatia'],
        areaInteresses: ['Educação', 'Tecnologia', 'Inovação'],
        localizacao: 'São Paulo, SP',
        experiencias: ['5 anos em desenvolvimento web', 'Líder de time em startup', 'Mentora de desenvolvedoras'],
        formacao: ['Bacharelado em Ciência da Computação', 'Bootcamp Full Stack'],
        certificacoes: ['AWS Certified', 'Google Cloud'],
        idiomas: ['Português', 'Inglês', 'Espanhol'],
        badges: ['Inovador', 'Mentor', 'Colaborador'],
        pontosGamificacao: 450,
        resumo: 'Apaixonada por código limpo e inclusão na tech. Buscando impacto social através da tecnologia.'
    },
    {
        id: 'user_bruno_costa',
        nome: 'Bruno Costa',
        email: 'bruno.costa@email.com',
        cargo: 'Engenheiro de Dados',
        habilidadesTecnicas: ['Python', 'SQL', 'Spark', 'Airflow', 'AWS'],
        softSkills: ['Análise Crítica', 'Atenção ao Detalhe', 'Resiliência'],
        areaInteresses: ['Big Data', 'Sustentabilidade', 'Tecnologia'],
        localizacao: 'Rio de Janeiro, RJ',
        experiencias: ['8 anos em data engineering', 'Projetos em energia renovável'],
        formacao: ['Mestrado em Engenharia'],
        certificacoes: ['Databricks Certified', 'AWS Data Analytics'],
        idiomas: ['Português', 'Inglês'],
        badges: ['Expert', 'Sustentável', 'Analista'],
        pontosGamificacao: 520,
        resumo: 'Transformando dados em insights para um mundo melhor. Entusiasta de energias renováveis.'
    },
    {
        id: 'user_camila_oliveira',
        nome: 'Camila Oliveira',
        email: 'camila.oliveira@email.com',
        cargo: 'Designer UX/UI',
        habilidadesTecnicas: ['Figma', 'Adobe XD', 'Prototipagem', 'HTML/CSS', 'JavaScript'],
        softSkills: ['Criatividade', 'Empatia com Usuário', 'Colaboração'],
        areaInteresses: ['Design Inclusivo', 'Educação', 'Acessibilidade'],
        localizacao: 'Belo Horizonte, MG',
        experiencias: ['6 anos em UX/UI', 'Projeto de redesign de app educativo'],
        formacao: ['Bacharelado em Design', 'Especialização em UX'],
        certificacoes: ['Nielsen Norman', 'Google UX Design'],
        idiomas: ['Português', 'Inglês'],
        badges: ['Designer', 'Inclusivo', 'Criativo'],
        pontosGamificacao: 400,
        resumo: 'Design que transforma vidas. Acredito em interfaces acessíveis para todos.'
    },
    {
        id: 'user_diego_mendes',
        nome: 'Diego Mendes',
        email: 'diego.mendes@email.com',
        cargo: 'Product Manager',
        habilidadesTecnicas: ['Analytics', 'User Research', 'Product Strategy', 'SQL básico'],
        softSkills: ['Liderança', 'Visão Estratégica', 'Comunicação Clara'],
        areaInteresses: ['Inovação', 'Inclusão Social', 'Produto'],
        localizacao: 'Curitiba, PR',
        experiencias: ['7 anos em product management', 'Lançamento de 5 produtos de sucesso'],
        formacao: ['MBA em Gestão de Produtos'],
        certificacoes: ['Google Product Manager', 'Reforge'],
        idiomas: ['Português', 'Inglês'],
        badges: ['Estratega', 'Líder', 'Inovador'],
        pontosGamificacao: 480,
        resumo: 'Construindo produtos que resolvem problemas reais e geram impacto.'
    },
    {
        id: 'user_elena_torres',
        nome: 'Elena Torres',
        email: 'elena.torres@email.com',
        cargo: 'Pesquisadora em IA/ML',
        habilidadesTecnicas: ['Python', 'TensorFlow', 'PyTorch', 'Deep Learning', 'NLP'],
        softSkills: ['Pesquisa', 'Pensamento Crítico', 'Inovação'],
        areaInteresses: ['Inteligência Artificial', 'Saúde', 'Ética em IA'],
        localizacao: 'Brasília, DF',
        experiencias: ['5 anos em pesquisa', 'Publicações em conferências internacionais'],
        formacao: ['Doutorado em Ciência da Computação'],
        certificacoes: ['Deep Learning Specialization'],
        idiomas: ['Português', 'Inglês'],
        badges: ['Pesquisador', 'Inovador', 'Ético'],
        pontosGamificacao: 520,
        resumo: 'Desenvolvendo IA responsável para solucionar problemas de saúde.'
    },
    {
        id: 'user_fernanda_lima',
        nome: 'Fernanda Lima',
        email: 'fernanda.lima@email.com',
        cargo: 'Desenvolvedora Frontend',
        habilidadesTecnicas: ['React', 'Vue.js', 'TypeScript', 'CSS', 'Webpack'],
        softSkills: ['Atenção ao Detalhe', 'Colaboração', 'Aprendizado Rápido'],
        areaInteresses: ['Frontend', 'Educação', 'Acessibilidade'],
        localizacao: 'Salvador, BA',
        experiencias: ['4 anos em frontend', 'Especialista em performance web'],
        formacao: ['Bootcamp Coding', 'Cursos online especializados'],
        certificacoes: ['React Certified', 'Google Web Developer'],
        idiomas: ['Português', 'Inglês'],
        badges: ['Frontend', 'Performance', 'Colaborador'],
        pontosGamificacao: 350,
        resumo: 'Criando experiências web incríveis e acessíveis.'
    },
    {
        id: 'user_gabriel_rocha',
        nome: 'Gabriel Rocha',
        email: 'gabriel.rocha@email.com',
        cargo: 'Desenvolvedor Backend',
        habilidadesTecnicas: ['Node.js', 'Java', 'PostgreSQL', 'Redis', 'Docker'],
        softSkills: ['Resolução de Problemas', 'Arquitetura de Sistemas'],
        areaInteresses: ['Backend', 'Sustentabilidade', 'Escalabilidade'],
        localizacao: 'Recife, PE',
        experiencias: ['6 anos em backend', 'Arquiteto de sistemas distribuídos'],
        formacao: ['Engenharia de Software'],
        certificacoes: ['Docker Certified', 'Kubernetes'],
        idiomas: ['Português', 'Inglês'],
        badges: ['Backend', 'Arquiteto', 'Escalável'],
        pontosGamificacao: 460,
        resumo: 'Construindo backends robustos e escaláveis para o mundo.'
    },
    {
        id: 'user_helena_santos',
        nome: 'Helena Santos',
        email: 'helena.santos@email.com',
        cargo: 'Especialista em Saúde Digital',
        habilidadesTecnicas: ['Health Tech', 'FHIR', 'API Design', 'Python'],
        softSkills: ['Empatia', 'Ética', 'Visão Humanitária'],
        areaInteresses: ['Saúde', 'Tecnologia', 'Inclusão Social'],
        localizacao: 'Manaus, AM',
        experiencias: ['5 anos em health tech', 'Projeto de telemedicina para comunidades remotas'],
        formacao: ['Engenharia Biomédica', 'Especialização em eHealth'],
        certificacoes: ['Health IT Certified'],
        idiomas: ['Português', 'Inglês'],
        badges: ['Humanitário', 'Inclusivo', 'Inovador'],
        pontosGamificacao: 430,
        resumo: 'Tecnologia ao serviço da saúde e da vida.'
    },
    {
        id: 'user_igor_martins',
        nome: 'Igor Martins',
        email: 'igor.martins@email.com',
        cargo: 'DevOps Engineer',
        habilidadesTecnicas: ['Kubernetes', 'AWS', 'CI/CD', 'Terraform', 'Monitoring'],
        softSkills: ['Organização', 'Documentação', 'Proatividade'],
        areaInteresses: ['Infraestrutura', 'Segurança', 'Automação'],
        localizacao: 'Florianópolis, SC',
        experiencias: ['7 anos em DevOps', 'Especialista em migração para cloud'],
        formacao: ['Engenharia de Computação'],
        certificacoes: ['AWS Solutions Architect', 'Kubernetes Admin'],
        idiomas: ['Português', 'Inglês'],
        badges: ['DevOps', 'Segurança', 'Nuvem'],
        pontosGamificacao: 490,
        resumo: 'Infraestrutura confiável é a base do sucesso digital.'
    },
    {
        id: 'user_julia_ferreira',
        nome: 'Julia Ferreira',
        email: 'julia.ferreira@email.com',
        cargo: 'Coordenadora de Projetos Sociais',
        habilidadesTecnicas: ['Project Management', 'Community Building', 'Excel'],
        softSkills: ['Liderança', 'Empatia', 'Organização', 'Networking'],
        areaInteresses: ['Inclusão Social', 'Educação', 'Comunidade'],
        localizacao: 'Fortaleza, CE',
        experiencias: ['6 anos em projetos sociais', '10+ programas educacionais liderados'],
        formacao: ['Administração Pública', 'Gestão Social'],
        certificacoes: ['Project Management Professional'],
        idiomas: ['Português', 'Inglês'],
        badges: ['Comunitário', 'Inclusivo', 'Líder'],
        pontosGamificacao: 420,
        resumo: 'Transformando comunidades através da educação e inclusão.'
    }
];

export const seedPublications = [
    {
        userId: 'user_alice_silva',
        userName: 'Alice Silva',
        content: 'Acabei de lançar meu novo projeto de educação em programação! Estou tão feliz em poder ajudar meninas a entrar na tech. Já temos 50 inscritas! 🚀',
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        likes: 87,
        comments: 12
    },
    {
        userId: 'user_bruno_costa',
        userName: 'Bruno Costa',
        content: 'A transição para energias renováveis é mais urgente do que nunca. Nosso novo projeto de análise de dados em energia solar já economizou 200 toneladas de CO2!',
        timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
        likes: 142,
        comments: 28
    },
    {
        userId: 'user_camila_oliveira',
        userName: 'Camila Oliveira',
        content: 'Redesign completo de app educativo focado em acessibilidade ♿ Agora 100% WCAG AA compliant! Inclusão no design não é opcional, é obrigação.',
        timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
        likes: 156,
        comments: 34
    },
    {
        userId: 'user_diego_mendes',
        userName: 'Diego Mendes',
        content: 'Aprendizado: Ouvir seus usuários é mais valioso que qualquer métrica. Mudei completamente a visão do produto após 20 entrevistas com usuários finais.',
        timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
        likes: 203,
        comments: 45
    },
    {
        userId: 'user_elena_torres',
        userName: 'Elena Torres',
        content: 'Publicado nosso novo paper em ética de IA na conferência ICML! O foco em viés algorítmico é fundamental para um futuro mais justo. 📄',
        timestamp: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
        likes: 98,
        comments: 22
    },
    {
        userId: 'user_fernanda_lima',
        userName: 'Fernanda Lima',
        content: 'Dica: Performance web importa! Otimizei um site e reduzi o tempo de carregamento de 8s para 2s. Resultado: aumento de 45% em conversão! ⚡',
        timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
        likes: 167,
        comments: 38
    },
    {
        userId: 'user_gabriel_rocha',
        userName: 'Gabriel Rocha',
        content: 'Arquitetura de microsserviços não é para todos. Aprendizado importante: complexidade bem colocada resolve problemas reais.',
        timestamp: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
        likes: 121,
        comments: 29
    },
    {
        userId: 'user_helena_santos',
        userName: 'Helena Santos',
        content: 'Telemedicina salva vidas! Nosso projeto atingiu comunidades em 5 cidades remotas. Já atendemos 1000 pacientes este ano. A tecnologia pode ser humanitária! ❤️',
        timestamp: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
        likes: 234,
        comments: 56
    },
    {
        userId: 'user_igor_martins',
        userName: 'Igor Martins',
        content: 'Zero downtime deployment é possível! Implementamos blue-green strategy e agora deployamos 10x por dia sem parar serviço 🔧',
        timestamp: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
        likes: 145,
        comments: 31
    },
    {
        userId: 'user_julia_ferreira',
        userName: 'Julia Ferreira',
        content: 'Celebrando 100 meninas formadas no programa de educação digital! Cada uma delas é uma multiplicadora de conhecimento em suas comunidades 🎓✨',
        timestamp: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
        likes: 289,
        comments: 67
    }
];

export const seedChallenges = [
    {
        titulo: 'Desenvolvimento de App Educativo Acessível',
        descricao: 'Criar um aplicativo móvel para ensino de programação com foco total em acessibilidade (WCAG AA). Inclui suporte a leitores de tela, modo escuro e múltiplas linguagens.',
        ods: ['Educação de Qualidade', 'Inclusão Social'],
        dificuldade: 'Avançado',
        tipo: 'Projeto',
        dataLimite: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
        pontos: 200,
        ownerId: 'user_alice_silva',
        participants: 5,
        likes: 34,
        comments: 8
    },
    {
        titulo: 'Dashboard de Análise de Energias Renováveis',
        descricao: 'Construir dashboard interativo que analisa dados de fontes renováveis, com previsões e recomendações de otimização de consumo.',
        ods: ['Sustentabilidade', 'Tecnologia', 'Energias Renováveis'],
        dificuldade: 'Intermediário',
        tipo: 'Projeto',
        dataLimite: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
        pontos: 150,
        ownerId: 'user_bruno_costa',
        participants: 3,
        likes: 28,
        comments: 6
    },
    {
        titulo: 'Redesign de Interface para Plataforma de Saúde',
        descricao: 'Redesenhar completamente a interface de um app de telemedicina para melhorar experiência de usuários idosos e com dificuldades motoras.',
        ods: ['Saúde e Bem-estar', 'Inclusão Social'],
        dificuldade: 'Intermediário',
        tipo: 'Projeto',
        dataLimite: new Date(Date.now() + 50 * 24 * 60 * 60 * 1000).toISOString(),
        pontos: 140,
        ownerId: 'user_camila_oliveira',
        participants: 4,
        likes: 42,
        comments: 10
    },
    {
        titulo: 'Otimização de Performance Web em E-commerce',
        descricao: 'Otimizar um site de e-commerce para reduzir tempo de carregamento em 70%, com foco em Core Web Vitals e experiência mobile.',
        ods: ['Tecnologia', 'Inovação'],
        dificuldade: 'Intermediário',
        tipo: 'Hackathon',
        dataLimite: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
        pontos: 120,
        ownerId: 'user_fernanda_lima',
        participants: 6,
        likes: 56,
        comments: 14
    },
    {
        titulo: 'Modelo de IA para Detecção de Doenças',
        descricao: 'Desenvolver modelo de machine learning que detecta padrões de doenças em dados médicos com 95%+ de acurácia, com foco em ética algorítmica.',
        ods: ['Saúde e Bem-estar', 'Tecnologia', 'Inovação'],
        dificuldade: 'Avançado',
        tipo: 'Projeto',
        dataLimite: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
        pontos: 250,
        ownerId: 'user_elena_torres',
        participants: 2,
        likes: 67,
        comments: 18
    },
    {
        titulo: 'Plataforma Comunitária de Conhecimento',
        descricao: 'Criar plataforma web para compartilhamento de conhecimento entre comunidades, com foco em inclusão digital e educação.',
        ods: ['Educação de Qualidade', 'Inclusão Social', 'Inovação'],
        dificuldade: 'Intermediário',
        tipo: 'Projeto',
        dataLimite: new Date(Date.now() + 75 * 24 * 60 * 60 * 1000).toISOString(),
        pontos: 160,
        ownerId: 'user_julia_ferreira',
        participants: 8,
        likes: 78,
        comments: 22
    },
    {
        titulo: 'Sistema de Backup e Recuperação em Cloud',
        descricao: 'Implementar sistema robusto de backup automático com recuperação de desastres (DR) em múltiplas regiões AWS.',
        ods: ['Tecnologia', 'Inovação'],
        dificuldade: 'Avançado',
        tipo: 'Projeto',
        dataLimite: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
        pontos: 180,
        ownerId: 'user_igor_martins',
        participants: 3,
        likes: 45,
        comments: 11
    },
    {
        titulo: 'Aplicativo de Monitoramento de Saúde Rural',
        descricao: 'Desenvolver app offline-first para comunidades rurais monitorar saúde básica, com sincronização quando houver internet.',
        ods: ['Saúde e Bem-estar', 'Inclusão Social', 'Educação de Qualidade'],
        dificuldade: 'Intermediário',
        tipo: 'Projeto',
        dataLimite: new Date(Date.now() + 55 * 24 * 60 * 60 * 1000).toISOString(),
        pontos: 140,
        ownerId: 'user_helena_santos',
        participants: 5,
        likes: 62,
        comments: 15
    },
    {
        titulo: 'Análise de Impacto Social de Iniciativas Tech',
        descricao: 'Estudar e documentar o impacto social de 10 projetos tech em comunidades carentes, gerando relatório e recomendações.',
        ods: ['Inclusão Social', 'Educação de Qualidade', 'Inovação'],
        dificuldade: 'Intermediário',
        tipo: 'Pesquisa',
        dataLimite: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
        pontos: 130,
        ownerId: 'user_diego_mendes',
        participants: 7,
        likes: 51,
        comments: 12
    },
    {
        titulo: 'Hackathon de Tecnologia Verde',
        descricao: 'Competição de 48h onde times criam soluções tecnológicas para problemas de sustentabilidade. Prêmios: mentorias + fundos para desenvolvimento.',
        ods: ['Sustentabilidade', 'Energias Renováveis', 'Inovação', 'Tecnologia'],
        dificuldade: 'Intermediário',
        tipo: 'Hackathon',
        dataLimite: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
        pontos: 200,
        ownerId: 'user_gabriel_rocha',
        participants: 15,
        likes: 124,
        comments: 31
    }
];
